add_rules('mode.debug')
add_repositories('Concerto-xrepo https://github.com/ConcertoEngine/xmake-repo.git main')
add_repositories('nazara-engine-repo https://github.com/NazaraEngine/xmake-repo.git')
add_requires('gtest', 'nlohmann_json', 'ConcertoCore')
add_requires('nazaraengine', { configs = { audio = false, network = false, physics2d = false, physics3d = false, utility = true, plugin_assimp = false, with_symbols = true  } })

target('Concerto')
    set_kind('binary')
    set_symbols('debug')
    set_warnings('everything')
    set_languages('cxx17')
    add_includedirs('include', 'include/ecs', 'include/math', 'include/ecs/systems', 'include/ecs/systems/nazaraRenderer', 'include/ecs/components')
    add_files('src/*.cpp', 'src/ecs/*.cpp', 'src/math/*.cpp', 'src/ecs/systems/*.cpp','src/ecs/systems/nazaraRenderer/*.cpp')
    set_optimize('none')
    add_packages('nlohmann_json', 'nazaraengine', 'ConcertoCore')
    after_build(function(target)
        print("Copying resources...")
        local binaryPath = "$(buildir)/$(plat)/$(arch)/$(mode)"
        os.mkdir(binaryPath .. "/assets")
        os.cp("config.json", binaryPath .. "/config.json")
        os.cp("assets/**", binaryPath .. "/assets")
        print("Copying resources... Done !")
    end)

target('ConcertoUnitTests')
    set_kind('binary')
    set_symbols('debug')
    set_warnings('everything')
    set_languages('cxx17')
    add_includedirs('include', 'include/ecs', 'include/math', 'include/ecs/systems')
    add_files('src/ecs/*.cpp', 'src/math/*.cpp', 'tests/*.cpp')
    add_packages('gtest', 'ConcertoCore')