add_rules('mode.debug')
add_repositories('nazara-engine-repo https://github.com/NazaraEngine/xmake-repo.git')
add_requires('gtest', 'nlohmann_json')
add_requires('nazaraengine', { configs = { audio = false, network = false, physics2d = false, physics3d = false, utility = false, with_symbols = true } })

target('Concerto')
set_kind('binary')
set_symbols('debug')
set_warnings('everything')
set_languages('cxx17')
add_includedirs('include', 'include/ecs', 'include/math', 'include/ecs/systems', 'include/ecs/systems/nazaraRenderer', 'include/ecs/components')
add_files('src/*.cpp', 'src/ecs/*.cpp', 'src/math/*.cpp', 'src/ecs/systems/*.cpp','src/ecs/systems/nazaraRenderer/*.cpp')
set_optimize('none')
add_packages('nlohmann_json', 'nazaraengine')
after_build(function(target)
    local binaryPath = "$(buildir)/$(plat)/$(arch)/$(mode)"
    os.mkdir(binaryPath .. "/assets")
    os.cp("config.json", binaryPath .. "/config.json")
    os.cp("assets/**", binaryPath .. "/assets")
end)

target('ConcertoUnitTests')
set_kind('binary')
set_symbols('debug')
set_warnings('everything')
set_languages('cxx17')
add_includedirs('include', 'include/ecs', 'include/math', 'include/ecs/systems')
add_files('src/ecs/*.cpp', 'src/math/*.cpp', 'tests/*.cpp')
add_packages('gtest')